# Generated by Django 4.2.7 on 2023-11-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appoinment',
            new_name='Appointment',
        ),
    ]
